# Load libraries

In [26]:
import pandas as pd
import numpy as np
import os
import re


# figures
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(color_codes = True)

%matplotlib inline

# Paths

In [27]:
analysispath = os.getcwd()
datapath = analysispath + '/../data/'

# Load data

In [28]:
data = pd.read_csv(datapath + 'holistic_face_abilities.csv')
subject_holistic_index_demographics = pd.read_csv('2_processed_holistic_index_demographics.csv', index_col=0)

In [29]:
subject_holistic_index_demographics.head()

,SUBJECTID,MTURKCODE,UPRIGHT,INVERTED,HOLISTIC_INDEX,AGE,GENDER,HISPANIC,RACE,PREVIOUS_EXPERIENCE
0,1,8958129,0.925,0.775,0.153846,26,Male,no,"White,Asian",no
1,2,3447207,0.925,0.750,0.153846,43,Male,no,White,no
2,3,8853818,0.950,0.725,0.230769,60,Female,no,White,I'm not sure
3,4,2631153,0.925,0.650,0.256410,35,Female,no,White,yes
4,5,6945018,0.925,0.725,0.179487,31,Male,no,White,no

In [30]:
data = data.drop([0, 1])
data.reset_index(inplace=True, drop=True)
data

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q197_Click Count,Q198,Q199_First Click,Q199_Last Click,Q199_Page Submit,Q199_Click Count,SC0,SC1,SC2,mTurkCode
0,2020-03-19 23:34:59,2020-03-19 23:57:17,IP Address,68.100.126.33,100,1338,True,2020-03-19 23:57:19,R_3iEZpvzRS9vKVaM,NaN,...,1,2,3.107,3.107,5.003,1,68,14,54,8958129
1,2020-03-19 23:38:00,2020-03-19 23:57:24,IP Address,67.245.214.21,100,1164,True,2020-03-19 23:57:25,R_2DNSpGKVGs7xijD,NaN,...,1,3,2.843,3.097,3.988,2,73,11,62,3447207
2,2020-03-19 23:41:00,2020-03-20 00:01:39,IP Address,50.25.69.85,100,1238,True,2020-03-20 00:01:40,R_3OfB0uYMa3qd1La,NaN,...,1,3,3.184,3.184,4.934,1,76,8,68,8853818
3,2020-03-19 23:38:08,2020-03-20 00:13:20,IP Address,172.93.164.64,100,2112,True,2020-03-20 00:13:25,R_XXJk6PeLtUH8BDX,NaN,...,1,3,3.395,3.395,4.582,1,63,24,39,2631153
4,2020-03-19 23:35:53,2020-03-20 00:17:48,IP Address,108.30.47.212,100,2514,True,2020-03-20 00:17:49,R_2wiCC5uOFWRFiIG,NaN,...,1,3,3.634,3.634,5.301,1,65,6,59,6945018
5,2020-03-19 23:50:07,2020-03-20 00:18:29,IP Address,24.155.198.221,100,1702,True,2020-03-20 00:18:30,R_Ania4tbinqj4erv,NaN,...,1,2,2.256,2.256,2.887,1,61,9,52,3158118
6,2020-03-20 00:36:17,2020-03-20 00:58:47,IP Address,64.137.80.190,100,1350,True,2020-03-20 00:58:49,R_2ONBPGGXtvd6Es9,NaN,...,1,3,2.544,2.544,3.606,1,86,23,63,8995867
7,2020-03-20 00:36:46,2020-03-20 00:59:38,IP Address,67.172.52.203,100,1371,True,2020-03-20 00:59:39,R_11ZnRiN938c6k9v,NaN,...,1,3,3.719,3.719,4.582,1,108,36,72,2476039
8,2020-03-20 00:35:30,2020-03-20 01:02:42,IP Address,45.4.197.71,100,1631,True,2020-03-20 01:02:43,R_2dGTovKMZRQowiC,NaN,...,2,1,3.526,3.526,4.375,1,74,25,49,9727504
9,2020-03-20 00:37:38,2020-03-20 01:04:14,IP Address,98.242.38.121,100,1596,True,2020-03-20 01:04:17,R_1C7v6X90kJK5sNv,NaN,...,1,2,2.434,2.434,3.355,1,67,16,51,3607546
10,2020-03-20 00:40:23,2020-03-20 01:05:38,IP Address,185.217.69.184,100,1515,True,2020-03-20 01:05:39,R_241QZfdYOgELHdr,NaN,...,2,1,2.227,2.227,3.926,1,63,13,50,9533352
11,2020-03-20 00:41:02,2020-03-20 01:05:40,IP Address,108.198.54.104,100,1478,True,2020-03-20 01:05:41,R_1gwhTByqkX6RuhZ,NaN,...,1,3,1.398,1.398,3.527,1,64,17,47,4918779
12,2020-03-20 00:43:10,2020-03-20 01:07:18,IP Address,185.33.85.152,100,1448,True,2020-03-20 01:07:19,R_b2UeyoXIogpfIjf,NaN,...,1,3,3.689,4.468,5.108,2,66,23,43,8848114
13,2020-03-20 00:41:27,2020-03-20 01:07:33,IP Address,172.93.164.92,100,1566,True,2020-03-20 01:07:34,R_0qDUudmSpmTYTiF,NaN,...,1,2,2.136,2.136,4.399,1,53,24,29,2596766
14,2020-03-20 00:36:04,2020-03-20 01:22:55,IP Address,69.234.141.157,100,2810,True,2020-03-20 01:22:56,R_RKReVS0hvBBpvfH,NaN,...,0,2,0,0,1.899,0,58,23,35,7023129
15,2020-03-20 00:35:58,2020-03-20 01:30:18,IP Address,74.99.64.129,100,3259,True,2020-03-20 01:30:19,R_2ansLCdTDviOFwN,NaN,...,1,2,2.112,2.112,2.848,1,59,23,36,215229
16,2020-03-20 01:34:16,2020-03-20 01:54:09,IP Address,172.93.164.81,100,1192,True,2020-03-20 01:54:10,R_bxsWJweDHbAATn3,NaN,...,1,3,6.358,6.358,7.418,1,79,25,54,8764208
17,2020-03-20 01:36:00,2020-03-20 02:15:19,IP Address,108.237.167.109,100,2358,True,2020-03-20 02:15:20,R_2zTN6gkpy5QUqTK,NaN,...,1,2,2.565,2.565,3.463,1,79,22,57,9195160
18,2020-03-20 01:54:48,2020-03-20 02:15:58,IP Address,23.226.130.234,100,1269,True,2020-03-20 02:15:59,R_9QzghaoW9OJIjrH,NaN,...,2,3,21.598,21.598,22.141,1,85,24,61,3017963
19,2020-03-20 01:37:51,2020-03-20 02:17:26,IP Address,24.107.216.210,100,2375,True,2020-03-20 02:17:27,R_1pWeJd3igwWHYiQ,NaN,...,1,2,3.17,3.17,3.994,1,69,28,41,7456000

# Column names

SC1 is AQ - SC2 is CFMT

In [31]:
AQ_column = 'SC1'
CFMT_column = 'SC2'

In [32]:
abilities_cols = [AQ_column, CFMT_column, 'mTurkCode']
abilities_data = data[abilities_cols].reset_index(drop=True)

# Assign abilities to subjects

In [35]:
for subject in subject_holistic_index_demographics.SUBJECTID.unique():
    
    # get mturkcode for that subject
    mturkcode = subject_holistic_index_demographics.loc[subject_holistic_index_demographics['SUBJECTID'] == subject, 'MTURKCODE'].reset_index(drop=True)[0]
    
    # get the original data for that subject
    subject_original_data = abilities_data[abilities_data['mTurkCode'] == str(mturkcode)]
    
    subject_holistic_index_demographics.loc[subject_holistic_index_demographics['SUBJECTID'] == subject, 'AQ'] = subject_original_data[AQ_column]
    subject_holistic_index_demographics.loc[subject_holistic_index_demographics['SUBJECTID'] == subject,'CFMT'] = subject_original_data[CFMT_column]

# Save data

This data now have holistic index, demographics, AQ and CFMT

In [38]:
subject_holistic_index_demographics.to_csv('3_processed_all.csv')